# Generated by Django 4.1.7 on 2024-09-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('city', models.CharField(blank=True, max_length=43, null=True)),
                ('club', models.CharField(blank=True, max_length=43, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('rating_fide', models.IntegerField(blank=True, default=1000, null=True)),
                ('rating_pzszach', models.IntegerField(blank=True, default=1000, null=True)),
                ('title_or_category', models.CharField(choices=[('GM', 'Grandmaster'), ('IM', 'International Master'), ('FM', 'FIDE Master'), ('CM', 'Candidate Master'), ('WGM', 'Woman Grandmaster'), ('WIM', 'Woman International Master'), ('WFM', 'Woman FIDE Master'), ('WCM', 'Woman Candidate Master'), ('M', 'Regional Master'), ('K', 'Regional Candidate Master'), ('I', 'Category I'), ('II', 'Category II'), ('III', 'Category III'), ('IV', 'Category IV'), ('V', 'Category V'), ('Bk', 'Bk')], default='None', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
