# Generated by Django 4.1.7 on 2024-09-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('previous_opponents', models.ManyToManyField(blank=True, to='tournaments.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('pace', models.CharField(choices=[('1', '1 min'), ('3', '3 min'), ('5', '5 min'), ('10', '10 min'), ('15', '15 min'), ('30', '30 min'), ('60', '60 min'), ('1+1', '1+1 sec'), ('3+2', '3+2 sec'), ('5+3', '5+3 sec'), ('10+5', '10+5 sec'), ('10+15', '10+15 sec'), ('15+15', '15+15 sec'), ('30+10', '30+10 sec'), ('60+30', '60+30 sec'), ('120+30', '120+30 sec')], max_length=10)),
                ('type_of_tournament', models.CharField(choices=[('Błyskawiczne', 'Błyskawiczne'), ('Szybkie', 'Szybkie'), ('Klasyczne', 'Klasyczne')], max_length=20)),
                ('status', models.CharField(choices=[('Nadchodzący', 'Nadchodzący'), ('Trwający', 'Trwający'), ('Zakończony', 'Zakończony')], max_length=12)),
                ('rounds_amount', models.IntegerField()),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('ranking', models.CharField(choices=[('Brak', 'Brak'), ('FIDE', 'FIDE'), ('PZSzach', 'PZSzach')], default='Brak', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, choices=[('dolnośląskie', 'Dolnośląskie'), ('kujawsko-pomorskie', 'Kujawsko-pomorskie'), ('lubelskie', 'Lubelskie'), ('lubuskie', 'Lubuskie'), ('łódzkie', 'Łódzkie'), ('małopolskie', 'Małopolskie'), ('mazowieckie', 'Mazowieckie'), ('opolskie', 'Opolskie'), ('podkarpackie', 'Podkarpackie'), ('podlaskie', 'Podlaskie'), ('pomorskie', 'Pomorskie'), ('śląskie', 'Śląskie'), ('świętokrzyskie', 'Świętokrzyskie'), ('warmińsko-mazurskie', 'Warmińsko-mazurskie'), ('wielkopolskie', 'Wielkopolskie'), ('zachodniopomorskie', 'Zachodniopomorskie')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis turnieju')),
                ('arbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbited_tournaments', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgianized_tournaments', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='tournaments', to='tournaments.player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('start_time', models.TextField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Runda',
                'verbose_name_plural': 'Rundy',
                'ordering': ['round_number'],
                'unique_together': {('tournament', 'round_number')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('1-0', '1-0'), ('0-1', '0-1'), ('0.5-0.5', '0.5-0.5')], max_length=10)),
                ('table_number', models.PositiveIntegerField()),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_matches', to='tournaments.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.round')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_matches', to='tournaments.player')),
            ],
        ),
    ]
