# Generated by Django 4.1.7 on 2024-09-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='start_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
