# Generated by Django 4.1.7 on 2024-09-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_player_start_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='achived_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
