# Generated by Django 4.1.7 on 2024-09-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_player_achived_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='achived_rating',
            new_name='achieved_rating',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rounds_amount',
            field=models.IntegerField(default=2),
        ),
    ]
