# Generated by Django 4.1.7 on 2024-09-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_rename_achived_rating_player_achieved_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='start_time',
        ),
    ]
