# Generated by Django 4.1.7 on 2024-09-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_remove_round_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='start_category',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
