# Generated by Django 4.1.7 on 2024-09-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_player_start_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avarage_oponents_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
