# Generated by Django 4.1.7 on 2024-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_player_avarage_oponents_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
