# Generated by Django 4.1.7 on 2024-09-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_player_has_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='consecutive_black_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='consecutive_white_games',
            field=models.IntegerField(default=0),
        ),
    ]
