# Generated by Django 4.1.7 on 2024-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_player_consecutive_black_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_color',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
