# Generated by Django 4.1.7 on 2024-09-20 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0015_player_last_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='arbiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arbited_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_begin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Nadchodzący', 'Nadchodzący'), ('Tr  wający', 'Trwający'), ('Zakończony', 'Zakończony')], default='Nadchodzący', max_length=12),
        ),
    ]
